#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v16
# autospec commit: b858a2a
#
Name     : msgpack-c
Version  : 6.0.2
Release  : 8
URL      : https://github.com/msgpack/msgpack-c/releases/download/c-6.0.2/msgpack-c-6.0.2.tar.gz
Source0  : https://github.com/msgpack/msgpack-c/releases/download/c-6.0.2/msgpack-c-6.0.2.tar.gz
Summary  : Binary-based efficient object serialization library
Group    : Development/Tools
License  : BSL-1.0
Requires: msgpack-c-lib = %{version}-%{release}
Requires: msgpack-c-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
`msgpack` for C
===================
Version 6.0.0 [![Build Status](https://github.com/msgpack/msgpack-c/workflows/CI/badge.svg?branch=c_master)](https://github.com/msgpack/msgpack-c/actions) [![Build status](https://ci.appveyor.com/api/projects/status/8kstcgt79qj123mw/branch/c_master?svg=true)](https://ci.appveyor.com/project/redboltz/msgpack-c/branch/c_master)
[![codecov](https://codecov.io/gh/msgpack/msgpack-c/branch/c_master/graph/badge.svg)](https://codecov.io/gh/msgpack/msgpack-c/branch/c_master)

%package dev
Summary: dev components for the msgpack-c package.
Group: Development
Requires: msgpack-c-lib = %{version}-%{release}
Provides: msgpack-c-devel = %{version}-%{release}
Requires: msgpack-c = %{version}-%{release}

%description dev
dev components for the msgpack-c package.


%package lib
Summary: lib components for the msgpack-c package.
Group: Libraries
Requires: msgpack-c-license = %{version}-%{release}

%description lib
lib components for the msgpack-c package.


%package license
Summary: license components for the msgpack-c package.
Group: Default

%description license
license components for the msgpack-c package.


%prep
%setup -q -n msgpack-c-6.0.2
cd %{_builddir}/msgpack-c-6.0.2
pushd ..
cp -a msgpack-c-6.0.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720579704
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720579704
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/msgpack-c
cp %{_builddir}/msgpack-c-%{version}/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/msgpack-c/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/msgpack.h
/usr/include/msgpack/fbuffer.h
/usr/include/msgpack/gcc_atomic.h
/usr/include/msgpack/object.h
/usr/include/msgpack/pack.h
/usr/include/msgpack/pack_define.h
/usr/include/msgpack/pack_template.h
/usr/include/msgpack/sbuffer.h
/usr/include/msgpack/sysdep.h
/usr/include/msgpack/timestamp.h
/usr/include/msgpack/unpack.h
/usr/include/msgpack/unpack_define.h
/usr/include/msgpack/unpack_template.h
/usr/include/msgpack/util.h
/usr/include/msgpack/version.h
/usr/include/msgpack/version_master.h
/usr/include/msgpack/vrefbuffer.h
/usr/include/msgpack/zbuffer.h
/usr/include/msgpack/zone.h
/usr/lib64/cmake/msgpack-c/msgpack-c-config-version.cmake
/usr/lib64/cmake/msgpack-c/msgpack-c-config.cmake
/usr/lib64/cmake/msgpack-c/msgpack-c-targets-relwithdebinfo.cmake
/usr/lib64/cmake/msgpack-c/msgpack-c-targets.cmake
/usr/lib64/libmsgpack-c.so
/usr/lib64/pkgconfig/msgpack-c.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libmsgpack-c.so.2.0.0
/usr/lib64/libmsgpack-c.so.2
/usr/lib64/libmsgpack-c.so.2.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/msgpack-c/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
